export const COMPANY_INFO = {
  name: "Atasa Danışmanlık",
  shortName: "Atasa",
  phone: "+90 850 308 69 98",
  email: "support@atasa.tr",
  emailAlt: "info@atasa.tr",
  website: "https://www.atasakurumsal.com.tr",
  foundedYear: 2012,
  experienceYears: 12,
  founder: "Ömer Habib",
  offices: {
    istanbul: {
      city: "İstanbul",
      address: "Mecidiyeköy mah. Raşit Rıza sk. Ahmet Esin İş Merkezi NO:4 K:2 D:7 Şişli/İstanbul",
      phone: "+90 850 308 69 98",
      googleMapsUrl: "https://www.google.com/maps/place/Atasa+Dan%C4%B1%C5%9Fmanl%C4%B1k+Hizmetleri+LTD.+%C5%9ET%C4%B0./@41.067297,28.9998846,17z/data=!4m6!3m5!1s0x14cab746724d84fd:0x1f99dbde2ff1d769!8m2!3d41.0672466!4d28.9998853!16s%2Fg%2F11rfcycng9",
    },
    askabat: {
      city: "Aşkabat",
      address: "Berkararlyk etrap / G.Kuliyev köçe/ Beyençli N70, Gat 3 309, Ashgabat, Türkmenistan",
      phone: "+993 637 816 52",
      googleMapsUrl: "",
    },
    baku: {
      city: "Bakü",
      address: "Tivi Plaza, Əhməd Rəcəbli Küçəsi, 1/10 Nəriman Nərimanov, Baku 1006, Azərbaycan",
      phone: "+994 51 823 44 10",
      googleMapsUrl: "",
    },
  },
  hours: {
    weekday: "09:00 - 18:00",
    saturday: "10:00 - 13:00",
    sunday: "Kapalı",
  },
  social: {
    youtube: "https://www.youtube.com/@atasa_tr",
    instagram: "https://www.instagram.com/atasa_tr/",
    tiktok: "https://www.tiktok.com/@atasa_tr",
    facebook: "https://www.facebook.com/atasa.consultancy",
  },
  stats: {
    workPermits: 1321,
    corporateClients: 1220,
    internationalReferences: 7,
    googleRating: 4.9,
    googleReviews: 150,
    youtubeFollowers: "100K+",
    instagramFollowers: "50K+",
  },
} as const;

export const NAV_LINKS = [
  { href: "/", label: "Ana Sayfa" },
  { href: "/hizmetlerimiz", label: "Hizmetlerimiz" },
  { href: "/hakkimizda", label: "Hakkımızda" },
  { href: "/referanslar", label: "Referanslar" },
  { href: "/blog", label: "Blog" },
  { href: "/sss", label: "SSS" },
  { href: "/iletisim", label: "İletişim" },
] as const;

export const SERVICES = [
  {
    id: "sektorel-danismanlik",
    title: "Sektörel Danışmanlık",
    description: "Turizmden sağlığa, eğitimden teknolojiye özel sektör dinamiklerine uygun terzi işi çalışma izni ve teşvik danışmanlığı.",
    href: "/sektorel-danismanlik",
    icon: "Target",
    color: "indigo",
  },
  {
    id: "yabanci-bakici-calisma-izni",
    title: "Yabancı Bakıcı Çalışma İzni",
    description: "Ev personeli, bebek ve yaşlı bakıcısı istihdamında yasal süreçlerin eksiksiz ve güvenli şekilde yönetilmesi.",
    href: "/yabanci-bakici-calisma-izni",
    icon: "Heart",
    color: "pink",
  },
  {
    id: "calisma-izni",
    title: "Yabancılara Çalışma İzni Alma",
    description: "Şirketiniz için yabancı personel çalışma izni başvurularını profesyonelce yönetiyoruz. %98 başarı oranı ile.",
    href: "/yabancilara-calisma-izni",
    icon: "Briefcase",
    color: "blue",
  },
  {
    id: "calisma-izni-uzatma",
    title: "Çalışma İzni Uzatma",
    description: "Mevcut çalışma izinlerinizin süresini zamanında ve sorunsuz uzatıyoruz. Süre takibi, belge hazırlığı.",
    href: "/calisma-izni-uzatma",
    icon: "RefreshCw",
    color: "emerald",
  },
  {
    id: "calisma-izni-transferi",
    title: "Çalışma İzni Transferi",
    description: "Personellerinizin şube veya işyeri değişikliğinde çalışma izni transferini hızla gerçekleştiriyoruz.",
    href: "/calisma-izni-transferi",
    icon: "ArrowRightLeft",
    color: "orange",
  },
  {
    id: "toplu-basvuru",
    title: "Kurumsal Toplu Başvuru",
    description: "50+ yabancı personel istihdam eden şirketlere özel toplu başvuru yönetimi. Dedicated destek.",
    href: "/toplu-basvuru",
    icon: "Building",
    color: "slate",
  },
  {
    id: "ikamet-izni",
    title: "İkamet İzni",
    description: "Kısa dönem, uzun dönem, öğrenci ve aile ikamet izni başvuru süreçlerinde tam destek.",
    href: "/ikamet-izni",
    icon: "Home",
    color: "cyan",
  },
  {
    id: "vatandaslik",
    title: "Vatandaşlık İşlemleri",
    description: "Yatırım yoluyla vatandaşlık başvurusu ve istisnai vatandaşlık süreçlerinde hukuki destek sağlıyoruz.",
    href: "/vatandaslik",
    icon: "Flag",
    color: "red",
  },
  {
    id: "sirket-kurulusu",
    title: "Yabancı Ortaklı Şirket Kuruluşu",
    description: "Türkiye'de yabancı ortaklı şirket kuruluş sürecinizi A'dan Z'ye yönetiyoruz. Tam destek.",
    href: "/sirket-kurulusu",
    icon: "Building2",
    color: "purple",
  },
  {
    id: "sgk-bordro",
    title: "SGK & Bordro Danışmanlık",
    description: "Yabancı personellerinizin SGK işlemleri, bordro hesaplamaları ve asgari ücret güncellemelerinde destek.",
    href: "/sgk-bordro",
    icon: "FileText",
    color: "violet",
  },
  {
    id: "turkuaz-kart",
    title: "Turkuaz Kart",
    description: "Nitelikli yabancılar için Turkuaz Kart başvuru sürecinde rehberlik ve hukuki destek.",
    href: "/turkuaz-kart",
    icon: "Landmark",
    color: "teal",
  },
] as const;

export const HERO_PHRASES = [
  "Çalışma İzni Alın",
  "Çalışma İzni Uzatın",
  "Çalışma İzni Transferi",
  "Toplu Başvuru Yapın",
  "Yasal Olarak Çalışın",
] as const;
